### PR TITLE
Bubbles up download failures from s3

### PR DESCRIPTION
**Pull request by eeyun**
Signed-off-by: Ian Henry <ihenry@chef.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
I would've approved it based on the branch name alone, but the code itself also looks good.

**Comment by raskchanky** [comment]
I notice we've gotten in the habit of merging things before Travis finishes running.  I'm not sure if this is a case-by-case thing or a general practice, but I think it's worth letting Travis runs finish, even for trivial PRs.

**Comment by chefsalim** [comment]
I'm probably the main offender.. but Travis is still in a broken state I believe..

**Pull request merged**
