### PR TITLE
Instrument (some) GitHub interactions

### PR DESCRIPTION
**Pull request by christophermaier**
To help track down our Github API rate limiting issues, this PR adds additional logging around webhook processing and Github App token generation, which should hopefully shed some light on what our heaviest authenticated requests are.

tenor-244187523

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by chefsalim** [comment]
Looks good - one comment - can we tag the debugs with a single searchable tag, eg, "GITCALL" so we can easily search all the known git calls in Sumologic.

**Comment by christophermaier** [comment]
Added "GITHUB-CALL" to all the token-generation log messages, and "GITHUB-WEBHOOK" to the webhook-related log messages, per @chefsalim's suggestion.

@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/builder/builds/348472644).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/builder/builds/348472644).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
