### PR TITLE
Use Gravatar for non-GitHub users

### PR DESCRIPTION
**Pull request by cnunciato**
This change makes user-profile avatars work thusly:

* If you’re signed in with GitHub, we’ll use whatever GitHub provides for you, as we do today.
* If you’re signed in by other means, and you’ve saved an e-mail address with your profile, we’ll use that address to retrieve your associated [Gravatar](http://en.gravatar.com/) image.
* Otherwise, we’ll use a default.

Also removes the unused `GravatarComponent`.

Signed-off-by: Christian Nunciato <chris@nunciato.org>

tenor-106270093

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by cnunciato** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/builder/builds/350487110).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/builder/builds/350487110).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
