### PR TITLE
Enable datadog monitoring for Builder #OPS-1773

### PR DESCRIPTION
**Pull request by Riju-vv**
Enabled datadog agent for shipping Logs and metrics. Set tags at service level.

Signed-off-by: Riju VV <riju.vv@progress.com>

### CODE REVIEW

**Review by mwrock — CHANGES_REQUESTED** [review]
I think the deletion of the package-lock.json was unintended. Correct?

**Comment by mwrock** [comment]
Have you confirmed that rebuilding these instances in the acceptance environment has the running data dog agent?

**Comment by Riju-vv** [comment]
> I think the deletion of the package-lock.json was unintended. Correct?

I was trying to remove the package-lock.json from the PR.

**Comment by Riju-vv** [comment]
> Have you confirmed that rebuilding these instances in the acceptance environment has the running data dog agent?

Some of the instances have datadog agent installed and running. This change will ensure that all instance have datadog agent installed and running including windows instances. And it will ship logs to datadog.

**Comment by mwrock** [comment]
Yeah I can definitely see the intent. I just want to make sure that you have actually tainted the worker nodes in acceptance, applied these changes and validated them.

**Comment by Rijuvv** [comment]
> Yeah I can definitely see the intent. I just want to make sure that you have actually tainted the worker nodes in acceptance, applied these changes and validated them.

Validated all changes in acceptance.

**Review by mwrock — APPROVED** [review]

**Pull request merged**
