### PR TITLE
Don't add audit entry for non-build

### PR DESCRIPTION
**Pull request by chefsalim**
Update job audit code to not write entry if a build is not actually issued (eg, for uploads that don't result in any builds being issued).

Signed-off-by: Salim Alam <salam@chef.io>

tenor-261897219

### CODE REVIEW

**Comment by raskchanky** [comment]
Would it be helpful to have an audit entry that specifically tells us there was no build, as a way to eliminate any ambiguity in the audit log?

**Comment by chefsalim** [comment]
Right, that's actually what we sort of get right now - entries with group id 0, that signifies no build.  80-90% of the current audit logging is basically this. It ends up being like an upload log, but not quite since it doesn't track builder uploads.  When (and if) we add upload audit, we'll probably not want to do it in the jobs audit table though, and for now, I'd rather not have no-op entries clutter up the jobs audit table.

**Comment by raskchanky** [comment]
Fair enough.

The DCO check looks like it's hung on this so I'm going to close the PR and re-open it to see if that fixes it.

**Pull request merged**
