### PR TITLE
Remove the "op" tool since we're on 1 schema now

### PR DESCRIPTION
**Pull request by raskchanky**
Signed-off-by: Josh Black <raskchanky@gmail.com>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
For those that don't know, the `op` tool was something I wrote to calculate what shard to look for, given either a database ID or a text string representing an origin name.  Now that we've merged all the shards into the public schema, this tool is useless.

**Comment by chefsalim** [comment]
The op tool has the base64 session token decode capability as well that is still valid use case.. also we may add more session token related tooling in the future, so might be better to just leave it as is for now... it might help debug shard issues for on-prem installations that have not migrated yet.

**Comment by raskchanky** [comment]
Ok, fair enough

**Pull request closed without merging**
