### PR TITLE
api raml update

### PR DESCRIPTION
**Pull request by pozsgaic**
Fix issue in format of original file
Manual convert to 1.0
Backfill missing content that is implemented in code

### CODE REVIEW

**Comment by mwrock** [comment]
Would it be possible to see the missing content additions and the conversion to 1.0 as separate commits or PRs. With do many changes, its hard to tell here what changed from the converter and what is a true content change.

**Comment by pozsgaic** [comment]
Sure - will do

**Comment by sajjaphani** [comment]
The following sub-routes have a **/depot** as a prefix.

/origins 
/pkgs 
/events 
/{origin}
/channels

Examples:
URI: /depot/{origin}/pkgs
Full URL: https://bldr.habitat.sh/v1/depot/{origin}/pkgs
URI: /depot/origins/{origin}
Full URL: https://bldr.habitat.sh/v1/depot/origins/{origin}

**Comment by pozsgaic** [comment]
I did observe that depot was not present.  Not sure if it was omitted intentionally in the baseline api.raml, but I opted not to
try to fix everything that was not done correctly.  I was aiming more to backfill missing content.

**Review by mwrock — APPROVED** [review]

**Pull request merged**
