### PR TITLE
Handle case where no pkgs have been built yet

### PR DESCRIPTION
**Pull request by scottopherson**
If a project w/ a connected plan has no built packages yet, the build button triggers a build for each possible platform. Fixes https://github.com/habitat-sh/builder/issues/1160

Signed-off-by: Scott Christopherson <scott@chef.io>

### CODE REVIEW

**Comment by scottopherson** [comment]
Not sure at the moment why linux2 job requests return 400. The query param used, `x86_64-linux-kernel2`, seems to be correct.

**Comment by chefsalim** [comment]
Looks good..  could we also add some unit and Cypress tests for this scenario

**Comment by scottopherson** [comment]
@chefsalim haha oops 🤦‍♂ Added tests for the other features but not any for the new feature in this PR!  Here's some for 'new project' case:

Screen Shot 2019-09-16 at 11 11 07 AM

**Comment by chefsalim** [comment]
Awesome, thanks @scottopherson

**Pull request merged**
