### PR TITLE
Add UI support for managing personal access tokens

### PR DESCRIPTION
**Pull request by cnunciato**
This change adds UI support for loading, creating and deleting personal access tokens. It’s behind a configuration entry (`enable_access_tokens`) and is disabled by default, as the API work to support it is currently under development.

Signed-off-by: Christian Nunciato <chris@nunciato.org>

tenor-192723110

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by chefsalim** [comment]
tenor-73544103

**Comment by ryankeairns** [comment]
giphy

**Comment by ryankeairns** [comment]
Looks great, I'm curious what you ended up with for the hidden state!

**Comment by cnunciato** [comment]
Oh, I just realized what you meant. 😄  It looks just like your design when a token exists, with the password-field treatment.

**Comment by cnunciato** [comment]
@thesentinels approve

**Comment by ryankeairns** [comment]
Fantastic, thanks!!

**Pull request merged**
