### PR TITLE
Remove upstream package syncing functionality

### PR DESCRIPTION
**Pull request by elliott-davis**
The overall design of this is confusing to users. For now, we are removing it
and will replace it with a standalone script/service that lets users sync
packages synchronously

Signed-off-by: Elliott Davis <elliott@excellent.io>

### CODE REVIEW

**Comment by thesentinels** [comment]
Thanks for the pull request! Here is what will happen next:
 1. Your PR will be reviewed by the maintainers
 2. If everything looks good, one of them will `approve` it, and your PR will be merged.

Thank you for contributing!

**Comment by raskchanky** [comment]
There's an issue that documents the confusing parts of this feature and improvements that could be made. https://github.com/habitat-sh/builder/issues/500

**Comment by elliott-davis** [comment]
So just for clarification on the commit message. @chefsalim is actively working on a stand-alone feature to sync packages on demand that should cover everything from #500. We're removing this functionality from the API now because it unblocks more of the simplification of services work around uploading packages.

**Comment by chefsalim** [comment]
I think we mis-designed this feature on a number of levels and we're going to be better off with a clean start with much clearer requirements and scenarios - both user facing as well as operational.  There are some fundamental issues that need to be resolved that will take some time.  In the meantime,  the lack of things like not syncing dependencies and keys means we can essentially leave depots in a bad state if a key package syncs but its deps are not present (until those are specifically searched for or attempted to be installed).  Adding more (potentially synchronous) code to do that sort of functionality as a background thread that lives in the UI nodes is not the model that I want to invest in.  Also the operational clarity for managing such a sync service needs to be better thought through than the logs we have now.  Net net, I think we are better off removing this code now, unblocking our simplification work, adding some scripts as a temporary bridge workaround until we get a solution in place that can be a delighter, and not worrying about sunk costs.

**Pull request merged**
