### PR TITLE
Remove Github and Permissions Config from sessionsrv

### PR DESCRIPTION
**Pull request by chefsalim**
Remove unused Github and Permissions config from sessionsrv.

Signed-off-by: Salim Alam <salam@chef.io>

### CODE REVIEW

**Comment by chefsalim** [comment]
thanks @baumanj !

**Comment by chefsalim** [comment]
@thesentinels approve

**Comment by thesentinels** [comment]
:metal: I am testing your branch against master before merging it. We do this to ensure that the master branch is never failing tests.

**Comment by thesentinels** [comment]
:neckbeard: Travis CI has [started testing this PR](https://travis-ci.org/habitat-sh/builder/builds/356409247).

**Comment by thesentinels** [comment]
:sparkling_heart: Travis CI [reports this PR passed](https://travis-ci.org/habitat-sh/builder/builds/356409247).

It always makes me feel nice when humans approve of one anothers work. I'm merging this PR now.

I just want you and the contributor to answer me one question:

gif-keyboard-3280869874741411265

**Pull request merged**
